version: '3.8'
services:
  backend:
    build:
      context: ./climax-server-springboot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/climax-client-average-salary
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    build:
      context: ./climax-client-react
    ports:
      - "3000:3000"

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=climax-client-average-salary
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
