server:
  port: 8080
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/climax-client-average-salary
    username: root
    password:
